version: '3.5'

services:
  mysql:
    build:
      context: ./
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"

volumes:
  mysql: