version: '3.1'

services:
  mysql:
    build: ./.docker
    image: mysql_local
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    container_name: $CONTAINER_NAME
    ports:
      - "3307:3306"
    volumes:
      - ./.docker/data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD
